// AUTO-GENERATED by Wails — DO NOT edit manually.
// This stub delegates to the Wails runtime bridge injected by the Go host.
// In development (wails dev), the Go host rewrites this file automatically.

import { Call } from '../../runtime/runtime.js'

export const CreateSession  = (cli, name, workDir, args, cols, rows) => Call('main.App.CreateSession', [cli, name, workDir, args, cols, rows])
export const ListSessions   = ()             => Call('main.App.ListSessions', [])
export const RenameSession  = (id, name)     => Call('main.App.RenameSession', [id, name])
export const KillSession    = (id)           => Call('main.App.KillSession', [id])
export const DetectCLIs     = ()             => Call('main.App.DetectCLIs', [])
// Phase 101-01 prerequisite — shell discovery via daemon /shells route.
export const ListShells              = ()    => Call('main.App.ListShells', [])
// Phase 101-01 — persisted "user has been warned about shell web-share" flag.
export const GetShellWebShareWarned  = ()    => Call('main.App.GetShellWebShareWarned', [])
export const SetShellWebShareWarned  = (v)   => Call('main.App.SetShellWebShareWarned', [v])
// Phase 150 SET-01 — warning-enabled master switch (default ON).
export const GetShellWebShareWarningEnabled = ()  => Call('main.App.GetShellWebShareWarningEnabled', [])
export const SetShellWebShareWarningEnabled = (v) => Call('main.App.SetShellWebShareWarningEnabled', [v])
// Phase 107-01 SHELL-11 — persisted shell binary path setting.
export const GetShellPath            = ()    => Call('main.App.GetShellPath', [])
export const SetShellPath            = (v)   => Call('main.App.SetShellPath', [v])
export const GetRelayPort            = ()    => Call('main.App.GetRelayPort', [])
export const UpdateCLIPath  = (name, path)   => Call('main.App.UpdateCLIPath', [name, path])

// Web serving bound methods
export const StartWebServer       = (port)                  => Call('main.App.StartWebServer', [port])
export const StopWebServer        = ()                      => Call('main.App.StopWebServer', [])
export const ToggleWebServing     = (sessionID, enabled)    => Call('main.App.ToggleWebServing', [sessionID, enabled])
// Phase 168 / FIX-02 (#117) — owner-only force-disconnect of all remote viewers.
export const DisconnectViewers    = (sessionID)             => Call('main.App.DisconnectViewers', [sessionID])
export const GetWebServerURL      = ()                      => Call('main.App.GetWebServerURL', [])
export const IsWebServerRunning   = ()                      => Call('main.App.IsWebServerRunning', [])

// CT disclosure bound methods
export const HasCTDisclosure        = ()                    => Call('main.App.HasCTDisclosure', [])
export const AcknowledgeCTDisclosure = ()                   => Call('main.App.AcknowledgeCTDisclosure', [])

// QR code and status bound methods
export const GetSessionQRCode     = (sessionID)             => Call('main.App.GetSessionQRCode', [sessionID])
export const GetWebServerQRCode   = ()                      => Call('main.App.GetWebServerQRCode', [])
export const GetSessionStatus     = (sessionID)             => Call('main.App.GetSessionStatus', [sessionID])
// Phase 132 / CARD-07 — throttled tail snapshot for Hub mini-preview. n clamped to [1..20].
export const GetSessionTailLines  = (id, n)                 => Call('main.App.GetSessionTailLines', [id, n])
// Phase 139 / CARD-05 — VT-emulator styled tail: per-cell color+bold grid. n clamped to [1..20].
export const GetSessionStyledTailLines = (id, n)            => Call('main.App.GetSessionStyledTailLines', [id, n])

// Daemon error and retry bound methods
export const GetDaemonError       = ()                      => Call('main.App.GetDaemonError', [])
export const RetryDaemon          = ()                      => Call('main.App.RetryDaemon', [])

// Directory dialog bound method
export const OpenDirectoryDialog  = (defaultDir)            => Call('main.App.OpenDirectoryDialog', [defaultDir])

// File dialog bound method (SET-04)
export const OpenFileDialog       = (defaultDir)            => Call('main.App.OpenFileDialog', [defaultDir])

// Tailscale health bound method
export const GetTailscaleStatus   = ()                      => Call('main.App.GetTailscaleStatus', [])

// Version bound method
export const GetVersion           = ()                      => Call('main.App.GetVersion', [])

// Update checker bound methods
export const GetLastUpdateInfo    = ()                      => Call('main.App.GetLastUpdateInfo', [])
export const CheckForUpdates      = ()                      => Call('main.App.CheckForUpdates', [])

// Remote sessions bound method
export const GetRemoteSessions    = ()                      => Call('main.App.GetRemoteSessions', [])

// Phase 130 — metadata-aware remote discovery (replaces GetRemoteSessions at the peers-poll site).
export const GetRemoteSessionsWithMeta = ()                 => Call('main.App.GetRemoteSessionsWithMeta', [])

// Phase 122-03 — remote-session file-browse join-code exchange + cap deposit.
export const ExchangeJoinCodeAtURL = (remoteBaseURL, code)  => Call('main.App.ExchangeJoinCodeAtURL', [remoteBaseURL, code])
export const RegisterRemoteCap     = (sessionID, baseURL, capToken) => Call('main.App.RegisterRemoteCap', [sessionID, baseURL, capToken])
// Phase 146-05 — held-cap reuse: read cap-bearing open URL from daemon RemoteCapStore.
export const OpenRemoteSessionURL  = (sessionID)            => Call('main.App.OpenRemoteSessionURL', [sessionID])

// Auto-install Tailscale bound method
export const AutoInstallTailscale = ()                      => Call('main.App.AutoInstallTailscale', [])

// Local network mode bound methods
export const GetLocalNetworkPassword = ()                   => Call('main.App.GetLocalNetworkPassword', [])
export const GetWebServerMode        = ()                   => Call('main.App.GetWebServerMode', [])

// CLI paths getter bound method (SET-01/02)
export const GetCLIPaths             = ()                   => Call('main.App.GetCLIPaths', [])

// Theme notification bound method
export const NotifyThemeChange       = ()                   => Call('main.App.NotifyThemeChange', [])

// Start-minimized bound methods (TRAY-02/03)
export const GetStartMinimized       = ()                   => Call('main.App.GetStartMinimized', [])
export const SetStartMinimized       = (val)                => Call('main.App.SetStartMinimized', [val])

// Auto-close session bound methods (SESS-01/02)
export const GetAutoCloseSession     = ()                   => Call('main.App.GetAutoCloseSession', [])
export const SetAutoCloseSession     = (val)                => Call('main.App.SetAutoCloseSession', [val])

// Notify-on-waiting bound methods (Phase 167 / NTF-04)
export const GetNotifyOnWaiting      = ()                   => Call('main.App.GetNotifyOnWaiting', [])
export const SetNotifyOnWaiting      = (val)                => Call('main.App.SetNotifyOnWaiting', [val])

// Stay-on-hub-after-create bound methods (Phase 168 / UX-01)
export const GetStayOnHubAfterCreate = ()                   => Call('main.App.GetStayOnHubAfterCreate', [])
export const SetStayOnHubAfterCreate = (val)                => Call('main.App.SetStayOnHubAfterCreate', [val])

// Plugin settings bound methods (PLUG-03 / Phase 92)
export const GetPluginSettings       = ()                   => Call('main.App.GetPluginSettings', [])
export const SetPluginSettings       = (s)                  => Call('main.App.SetPluginSettings', [s])

// Find-bar search-config sub-key writer (Phase 94-07 / WR-03 gap closure).
export const SetSearchConfig         = (cfg)                => Call('main.App.SetSearchConfig', [cfg])

// Web-links sub-key writer (Phase 95 LNK-05 / LNK-06).
export const SetWebLinksConfig       = (cfg)                => Call('main.App.SetWebLinksConfig', [cfg])

// Image-addon sub-key writer (Phase 96 IMG-02).
export const SetImageConfig          = (cfg)                => Call('main.App.SetImageConfig', [cfg])

// Save terminal session (Phase 97 SER-01).
export const SaveTerminalSession    = (defaultDir, defaultName, content) => Call('main.App.SaveTerminalSession', [defaultDir, defaultName, content])

// Phase 120 UAT-1 — server-side file download bypassing webview <a download>.
export const DownloadFile           = (url, suggestedName)   => Call('main.App.DownloadFile', [url, suggestedName])

// Set tray progress quartile (Phase 98 PRG-03).
export const SetTrayProgress        = (quartile)                => Call('main.App.SetTrayProgress', [quartile])

// Quit confirmation bound methods (APP-01/02)
export const QuitGUIOnly             = ()                   => Call('main.App.QuitGUIOnly', [])
export const QuitAll                 = ()                   => Call('main.App.QuitAll', [])

// Phase 87 capability bound methods (SEC-01..SEC-05)
export const IssueCapabilities       = (sessionID)          => Call('main.App.IssueCapabilities', [sessionID])
export const ExchangeJoinCode        = (code)               => Call('main.App.ExchangeJoinCode', [code])
export const RegenerateSigningKey    = ()                   => Call('main.App.RegenerateSigningKey', [])
export const GetCapabilityQRCode     = (joinURL)            => Call('main.App.GetCapabilityQRCode', [joinURL])

// Phase 137 / SHARE-03: per-session browse toggle (owner binding). Replaces SetSessionFilesWrite (D-02/D-07).
export const SetSessionBrowse        = (sessionID, enabled) => Call('main.App.SetSessionBrowse', [sessionID, enabled])

// Phase 165 / FNL-01 — Funnel enable/disable with auto-expiry (expiresIn=0 = no expiry).
export const SetSessionFunnel = (sessionID, enabled, expiresIn) => Call('main.App.SetSessionFunnel', [sessionID, enabled, expiresIn])
