// AUTO-GENERATED by Wails — DO NOT edit manually.
// This stub delegates to the Wails runtime bridge injected by the Go host.
// In development (wails dev), the Go host rewrites this file automatically.

import { Call } from '../../runtime/runtime.js'

export const CreateSession  = (cli, name)    => Call('main.App.CreateSession', [cli, name])
export const ListSessions   = ()             => Call('main.App.ListSessions', [])
export const RenameSession  = (id, name)     => Call('main.App.RenameSession', [id, name])
export const KillSession    = (id)           => Call('main.App.KillSession', [id])
export const DetectCLIs     = ()             => Call('main.App.DetectCLIs', [])
export const GetRelayPort   = ()             => Call('main.App.GetRelayPort', [])
export const UpdateCLIPath  = (name, path)   => Call('main.App.UpdateCLIPath', [name, path])
