// AUTO-GENERATED by Wails — DO NOT edit manually.
// This stub is replaced by `wails dev` / `wails build` at runtime.

import { daemon } from '../models'

export interface SessionInfo {
  id: string
  cli: string
  name: string
  state: string
  status: string
  createdAt: string
  hostname: string
  webEnabled: boolean
  viewerCount: number
  exitCode?: number
  duration?: number
  /** Phase 124 / CAP-06: true when the session cwd equals EvalSymlinks($HOME). Server-side source of truth for the home-dir write warning on both GUI and TUI. */
  homeDir: boolean
  /** Phase 124 / CAP-04: true when the per-session owner write toggle is ON. Server-side source of truth for cross-surface parity. */
  filesWrite: boolean
  /** Phase 131 / GRID-02: EvalSymlinks-resolved session working directory. Used by the Hub to group session cards by working directory. */
  workDir: string
}

export interface DetectedCLI {
  Name: string
  Path: string
}

export function CreateSession(cli: string, name: string, workDir: string, args: string[], cols: number, rows: number): Promise<string>
export function ListSessions(): Promise<SessionInfo[]>
export function RenameSession(id: string, name: string): Promise<void>
export function KillSession(id: string): Promise<void>
export function DetectCLIs(): Promise<DetectedCLI[]>
// Phase 101-01 prerequisite — shell discovery via daemon /shells route.
export function ListShells(): Promise<daemon.DetectedShell[]>
// Phase 101-01 — persisted "user has been warned about shell web-share" flag.
export function GetShellWebShareWarned(): Promise<boolean>
export function SetShellWebShareWarned(v: boolean): Promise<void>
// Phase 107-01 SHELL-11 — persisted shell binary path setting.
export function GetShellPath(): Promise<string>
export function SetShellPath(v: string): Promise<void>
export function GetRelayPort(): Promise<number>
export function UpdateCLIPath(name: string, path: string): Promise<void>

// Web serving bound methods
export function StartWebServer(port: number): Promise<void>
export function StopWebServer(): Promise<void>
export function ToggleWebServing(sessionID: string, enabled: boolean): Promise<void>
export function GetWebServerURL(): Promise<string>
export function IsWebServerRunning(): Promise<boolean>

// CT disclosure bound methods
export function HasCTDisclosure(): Promise<boolean>
export function AcknowledgeCTDisclosure(): Promise<void>

// QR code and status bound methods
export function GetSessionQRCode(sessionID: string): Promise<string>
export function GetWebServerQRCode(): Promise<string>
export function GetSessionStatus(sessionID: string): Promise<string>
// Phase 132 / CARD-07 — throttled tail snapshot for Hub mini-preview. n clamped to [1..20].
export function GetSessionTailLines(id: string, n: number): Promise<string[]>

// Daemon error and retry bound methods
export function GetDaemonError(): Promise<string>
export function RetryDaemon(): Promise<void>

// Directory dialog bound method
export function OpenDirectoryDialog(defaultDir: string): Promise<string>

// File dialog bound method (SET-04)
export function OpenFileDialog(defaultDir: string): Promise<string>

// Version bound method
export function GetVersion(): Promise<string>

// Update checker bound methods
export function GetLastUpdateInfo(): Promise<{
  currentVersion: string;
  latestVersion: string;
  releaseURL: string;
} | null>
export function CheckForUpdates(): Promise<{
  currentVersion: string;
  latestVersion: string;
  releaseURL: string;
} | null>

// Tailscale health bound method
export function GetTailscaleStatus(): Promise<{
  installed: boolean
  connected: boolean
  hasCerts: boolean
  ip: string
  domain: string
  binaryFound: boolean
  daemonUp: boolean
  platformHint: string
}>

// Remote sessions bound method
export interface RemoteSession {
  id: string
  name: string
  cliType: string
  status: string
  url: string
}

export interface RemotePeerSessions {
  hostname: string
  /** Phase 130 — true when the peer responded to the /api/sessions/meta probe; false when unreachable. */
  reachable: boolean
  sessions: RemoteSession[]
}

export function GetRemoteSessions(): Promise<RemotePeerSessions[]>
// Phase 130 — replaces GetRemoteSessions at the peers-poll site in App.tsx.
// Returns ALL probed peers (including unreachable + zero-session ones) so the
// Remote Sessions panel can render honest per-peer states (RB-01, RB-04).
export function GetRemoteSessionsWithMeta(): Promise<RemotePeerSessions[]>

// Phase 122-03 — remote-session file-browse join-code exchange + cap deposit.
export function ExchangeJoinCodeAtURL(remoteBaseURL: string, code: string): Promise<string>
export function RegisterRemoteCap(sessionID: string, baseURL: string, capToken: string): Promise<void>

// Auto-install Tailscale bound method
export function AutoInstallTailscale(): Promise<void>

// Local network mode bound methods
export function GetLocalNetworkPassword(): Promise<string>
export function GetWebServerMode(): Promise<string>

// CLI paths getter bound method (SET-01/02)
export function GetCLIPaths(): Promise<Record<string, string>>

// Theme notification bound method
export function NotifyThemeChange(): Promise<void>

// Start-minimized bound methods (TRAY-02/03)
export function GetStartMinimized(): Promise<boolean>
export function SetStartMinimized(val: boolean): Promise<void>

// Auto-close session bound methods (SESS-01/02)
export function GetAutoCloseSession(): Promise<boolean>
export function SetAutoCloseSession(val: boolean): Promise<void>

// Plugin settings bound methods (PLUG-03 / Phase 92)
export function GetPluginSettings(): Promise<daemon.PluginSettings>
export function SetPluginSettings(arg1: daemon.PluginSettings): Promise<void>

// Find-bar search-config sub-key writer (Phase 94-07 / WR-03 gap closure).
// Persists ONLY the SearchConfig sub-key of PluginSettings, leaving the
// other plugin fields untouched. Re-emits "settings:plugins" with the
// full PluginSettings post-write so the existing App.tsx listener fires.
export function SetSearchConfig(arg1: daemon.SearchConfig): Promise<void>

// Web-links sub-key writer (Phase 95 LNK-05 / LNK-06). Persists ONLY the
// WebLinksConfig sub-key of PluginSettings, leaving the other plugin
// fields untouched. Re-emits "settings:plugins" with the full
// PluginSettings post-write so the existing App.tsx listener fires.
export function SetWebLinksConfig(arg1: daemon.WebLinksConfig): Promise<void>

// Image-addon sub-key writer (Phase 96 IMG-02). Persists ONLY the
// ImageConfig sub-key of PluginSettings, leaving the other plugin
// fields untouched. Re-emits "settings:plugins" with the full
// PluginSettings post-write so the existing App.tsx listener fires.
export function SetImageConfig(arg1: daemon.ImageConfig): Promise<void>

// Save terminal session (Phase 97 SER-01).
export function SaveTerminalSession(defaultDir: string, defaultName: string, content: string): Promise<void>

// Phase 120 UAT-1 — server-side file download with native SaveFileDialog,
// bypassing the Wails WKWebView's ignore-the-<a-download>-attribute behavior.
export function DownloadFile(url: string, suggestedName: string): Promise<void>

// Set tray progress quartile (Phase 98 PRG-03).
export function SetTrayProgress(quartile: number): Promise<void>

// Quit confirmation bound methods (APP-01/02)
export function QuitGUIOnly(): Promise<void>
export function QuitAll(): Promise<void>

// Phase 87 capability bound methods (SEC-01..SEC-05)
export interface IssueCapabilitiesResponse {
  readUrl: string
  writeUrl: string
  readCode: string
  writeCode: string
  homeDir: boolean  // Phase 124 / CAP-06: true when session cwd == EvalSymlinks($HOME)
}
export function IssueCapabilities(sessionID: string): Promise<IssueCapabilitiesResponse>
export function ExchangeJoinCode(code: string): Promise<string>
export function RegenerateSigningKey(): Promise<void>
export function GetCapabilityQRCode(joinURL: string): Promise<string>

// Phase 124 / CAP-04: per-session file-write toggle (owner binding).
export function SetSessionFilesWrite(sessionID: string, enabled: boolean): Promise<void>
