// AUTO-GENERATED by Wails — DO NOT edit manually.
// This stub is replaced by `wails dev` / `wails build` at runtime.

export interface SessionInfo {
  id: string
  cli: string
  name: string
  state: string
  createdAt: string
}

export interface DetectedCLI {
  Name: string
  Path: string
}

export function CreateSession(cli: string, name: string, workDir: string, args: string[], cols: number, rows: number): Promise<string>
export function ListSessions(): Promise<SessionInfo[]>
export function RenameSession(id: string, name: string): Promise<void>
export function KillSession(id: string): Promise<void>
export function DetectCLIs(): Promise<DetectedCLI[]>
export function GetRelayPort(): Promise<number>
export function UpdateCLIPath(name: string, path: string): Promise<void>

// Web serving bound methods
export function StartWebServer(port: number): Promise<void>
export function StopWebServer(): Promise<void>
export function ToggleWebServing(sessionID: string, enabled: boolean): Promise<void>
export function GetWebServerURL(): Promise<string>
export function IsWebServerRunning(): Promise<boolean>

// CT disclosure bound methods
export function HasCTDisclosure(): Promise<boolean>
export function AcknowledgeCTDisclosure(): Promise<void>

// QR code and status bound methods
export function GetSessionQRCode(sessionID: string): Promise<string>
export function GetSessionStatus(sessionID: string): Promise<string>

// Daemon error and retry bound methods
export function GetDaemonError(): Promise<string>
export function RetryDaemon(): Promise<void>

// Directory dialog bound method
export function OpenDirectoryDialog(defaultDir: string): Promise<string>

// Tailscale health bound method
export function GetTailscaleStatus(): Promise<{
  installed: boolean
  connected: boolean
  hasCerts: boolean
  ip: string
  domain: string
}>
