// AUTO-GENERATED by Wails — DO NOT edit manually.
// This stub is replaced by `wails dev` / `wails build` at runtime.

export interface SessionInfo {
  id: string
  cli: string
  name: string
  state: string
  createdAt: string
}

export interface DetectedCLI {
  Name: string
  Path: string
}

export interface NetworkInterface {
  Name: string
  IP: string
  IsTailscale: boolean
}

export function CreateSession(cli: string, name: string): Promise<string>
export function ListSessions(): Promise<SessionInfo[]>
export function RenameSession(id: string, name: string): Promise<void>
export function KillSession(id: string): Promise<void>
export function DetectCLIs(): Promise<DetectedCLI[]>
export function GetRelayPort(): Promise<number>
export function UpdateCLIPath(name: string, path: string): Promise<void>

// Web serving bound methods
export function SetWebPassword(password: string): Promise<void>
export function IsWebPasswordSet(): Promise<boolean>
export function GetNetworkInterfaces(): Promise<NetworkInterface[]>
export function StartWebServer(bindIP: string, port: number): Promise<void>
export function StopWebServer(): Promise<void>
export function ToggleWebServing(sessionID: string, enabled: boolean): Promise<void>
export function GenerateSessionToken(sessionID: string): Promise<string>
export function GetWebServerURL(): Promise<string>
export function GetCACertPath(): Promise<string>
export function IsWebServerRunning(): Promise<boolean>

// QR code and status bound methods
export function GetSessionQRCode(sessionID: string): Promise<string>
export function GetSessionStatus(sessionID: string): Promise<string>
