// AUTO-GENERATED by Wails — DO NOT edit manually.
// This stub delegates to the Wails runtime bridge injected by the Go host.
// In development (wails dev), the Go host rewrites this file automatically.

import { Call } from '../../runtime/runtime.js'

export const CreateSession  = (cli, name)    => Call('main.App.CreateSession', [cli, name])
export const ListSessions   = ()             => Call('main.App.ListSessions', [])
export const RenameSession  = (id, name)     => Call('main.App.RenameSession', [id, name])
export const KillSession    = (id)           => Call('main.App.KillSession', [id])
export const DetectCLIs     = ()             => Call('main.App.DetectCLIs', [])
export const GetRelayPort   = ()             => Call('main.App.GetRelayPort', [])
export const UpdateCLIPath  = (name, path)   => Call('main.App.UpdateCLIPath', [name, path])

// Web serving bound methods
export const SetWebPassword       = (password)              => Call('main.App.SetWebPassword', [password])
export const IsWebPasswordSet     = ()                      => Call('main.App.IsWebPasswordSet', [])
export const GetNetworkInterfaces = ()                      => Call('main.App.GetNetworkInterfaces', [])
export const StartWebServer       = (bindIP, port)          => Call('main.App.StartWebServer', [bindIP, port])
export const StopWebServer        = ()                      => Call('main.App.StopWebServer', [])
export const ToggleWebServing     = (sessionID, enabled)    => Call('main.App.ToggleWebServing', [sessionID, enabled])
export const GenerateSessionToken = (sessionID)             => Call('main.App.GenerateSessionToken', [sessionID])
export const GetWebServerURL      = ()                      => Call('main.App.GetWebServerURL', [])
export const GetCACertPath        = ()                      => Call('main.App.GetCACertPath', [])
export const IsWebServerRunning   = ()                      => Call('main.App.IsWebServerRunning', [])

// QR code and status bound methods
export const GetSessionQRCode     = (sessionID)             => Call('main.App.GetSessionQRCode', [sessionID])
export const GetSessionStatus     = (sessionID)             => Call('main.App.GetSessionStatus', [sessionID])
