// Auto-generated by Wails (`wails generate module`) and pinned in-repo.
// This file mirrors the `daemon.PluginSettings` Go struct surfaced through
// the (*App).GetPluginSettings / SetPluginSettings Wails bindings (PLUG-03).
//
// Plan 92-03 imports `PluginSettings` from `../wailsjs/go/models` — keep this
// file in sync with `internal/daemon/plugin_settings.go` (json tags must match).

export namespace daemon {

	export class SearchConfig {
	    regex: boolean;
	    caseSensitive: boolean;
	    wholeWord: boolean;

	    static createFrom(source: any = {}) {
	        return new SearchConfig(source);
	    }

	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.regex = source["regex"];
	        this.caseSensitive = source["caseSensitive"];
	        this.wholeWord = source["wholeWord"];
	    }
	}

	// Phase 95 LNK-02/LNK-03/LNK-05: nested per-plugin runtime config
	// for the web-links toggle. Defaults: modifier="platform" +
	// ALL confirmations true (security-first; daemon owns defaults via
	// internal/daemon/plugin_settings.go defaultPluginSettings()).
	export class WebLinksConfig {
	    modifier: string;
	    confirmOSC8: boolean;
	    confirmIDN: boolean;
	    confirmTyposquat: boolean;

	    static createFrom(source: any = {}) {
	        return new WebLinksConfig(source);
	    }

	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.modifier = source["modifier"];
	        this.confirmOSC8 = source["confirmOSC8"];
	        this.confirmIDN = source["confirmIDN"];
	        this.confirmTyposquat = source["confirmTyposquat"];
	    }
	}

	// Phase 96 IMG-02: nested per-plugin runtime config for the inline-image
	// addon. Single field for now; daemon owns defaults via
	// internal/daemon/plugin_settings.go defaultPluginSettings()
	// (StorageLimit defaults to 16 MB).
	export class ImageConfig {
	    storageLimit: number;

	    static createFrom(source: any = {}) {
	        return new ImageConfig(source);
	    }

	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.storageLimit = source["storageLimit"];
	    }
	}

	export class PluginSettings {
	    webgl: boolean;
	    unicode11: boolean;
	    search: boolean;
	    searchConfig: SearchConfig;
	    webLinks: boolean;
	    webLinksConfig: WebLinksConfig;
	    image: boolean;
	    imageConfig: ImageConfig;
	    serialize: boolean;
	    clipboard: boolean;
	    progress: boolean;

	    static createFrom(source: any = {}) {
	        return new PluginSettings(source);
	    }

	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.webgl = source["webgl"];
	        this.unicode11 = source["unicode11"];
	        this.search = source["search"];
	        // Phase 94 SRC-02: nested SearchConfig — inline conversion (no
	        // convertValues helper member, which would surface as keyof
	        // PluginSettings and break PluginsSection.tsx toggle iteration).
	        this.searchConfig = source["searchConfig"]
	            ? new SearchConfig(source["searchConfig"])
	            : new SearchConfig();
	        this.webLinks = source["webLinks"];
	        // Phase 95 LNK-02: nested WebLinksConfig — same inline pattern as
	        // SearchConfig above (avoid `convertValues` helper that would
	        // surface as `keyof PluginSettings`).
	        this.webLinksConfig = source["webLinksConfig"]
	            ? new WebLinksConfig(source["webLinksConfig"])
	            : new WebLinksConfig();
	        this.image = source["image"];
	        // Phase 96 IMG-02: nested ImageConfig — same inline pattern as
	        // SearchConfig / WebLinksConfig above (avoid `convertValues`
	        // helper that would surface as `keyof PluginSettings`).
	        this.imageConfig = source["imageConfig"]
	            ? new ImageConfig(source["imageConfig"])
	            : new ImageConfig();
	        this.serialize = source["serialize"];
	        this.clipboard = source["clipboard"];
	        this.progress = source["progress"];
	    }
	}

}
