// AUTO-GENERATED by Wails — DO NOT edit manually.
// In production, Wails injects `window.go` and `window.wails` into the WebView.
// This stub forwards calls to that bridge.

export function Call(method, args) {
  // Wails v2 runtime bridge: window.go[pkg][method](...args)
  const parts = method.split('.')
  // parts = ['main', 'App', 'MethodName']
  const pkg = parts[0]
  const klass = parts[1]
  const fn = parts[2]
  if (window.go && window.go[pkg] && window.go[pkg][klass] && window.go[pkg][klass][fn]) {
    return window.go[pkg][klass][fn](...args)
  }
  return Promise.reject(new Error(`Wails bridge not available for ${method}`))
}

export function EventsOn(eventName, callback) {
  if (window.runtime && window.runtime.EventsOn) {
    return window.runtime.EventsOn(eventName, callback)
  }
}

export function EventsOff(eventName) {
  if (window.runtime && window.runtime.EventsOff) {
    return window.runtime.EventsOff(eventName)
  }
}
